apiVersion: v2
name: opendj
description: OpenDJ is an LDAPv3 compliant directory service
type: application
maintainers:
- name: Itay Shechter
  email: itaylcars@hotmail.com
keywords:
- kubernetes
- database
- opendj
- ldap
icon: https://raw.githubusercontent.com/OpenIdentityPlatform/OpenDJ/master/logo.png
home: http://www.openidentityplatform.org
sources:
- https://github.com/OpenIdentityPlatform/OpenDJ
- https://github.com/itay47/helm-charts/charts/opendj
- https://github.com/arhat-dev/helm-charts
version: 0.0.3
# docker-image: docker.io/openidentityplatform/opendj
appVersion: 4.4.11
